import type { DemoTemplateManifestRecord, DemoTemplateVisualDescriptor } from '@/types/workflow';

export const DEMO_VISUAL_TEMPLATES: DemoTemplateVisualDescriptor[] = [
  { id: 'modern', name: '现代商务', description: '简洁中性，信息密度均衡，适合通用企业演示。' },
  { id: 'elegant', name: '浅色商务', description: '浅色留白，稳重克制，适合对外展示与管理后台。' },
  { id: 'elegant-dark', name: '深色商务', description: '深色成熟，强调专业感与高层视图。' },
];

export const DEMO_TEMPLATE_MANIFESTS: DemoTemplateManifestRecord[] = [
  {
    id: 'ops-center',
    name: '运营管理中心',
    description: '适合运营后台、项目管理、工单处理、内部协同管理。',
    productCategory: 'admin-console',
    appShell: 'sidebar-dashboard',
    pageBlueprints: ['工作台', '任务列表', '详情页', '处理表单', '统计概览'],
    navigationStrategy: '左侧导航 + 顶部工具栏 + 主内容区',
    interactionPatterns: ['筛选', '列表操作', '详情联动', '处理动作', '统计卡片'],
    dataStrategy: '模块化记录数据 + 本地存储',
    seedDataStrategy: '运营任务与处理记录',
    developerPromptHints: ['突出待办与处理效率', '强调列表到详情的闭环', '保持企业后台的克制风格'],
  },
  {
    id: 'crm-backoffice',
    name: '客户运营后台',
    description: '适合客户管理、销售线索、商机跟进、客户服务运营。',
    productCategory: 'admin-console',
    appShell: 'sidebar-dashboard',
    pageBlueprints: ['客户看板', '客户列表', '商机详情', '跟进表单', '转化分析'],
    navigationStrategy: '左侧导航 + 主工作区 + 顶部快捷操作',
    interactionPatterns: ['客户筛选', '状态跟进', '详情记录', '表单录入', '指标分析'],
    dataStrategy: '客户记录 + 跟进数据 + 本地存储',
    seedDataStrategy: '客户与商机记录',
    developerPromptHints: ['强调客户阶段推进', '突出线索与转化信息', '避免泛化成通用资产台账'],
  },
  {
    id: 'bi-analysis',
    name: '经营分析驾驶舱',
    description: '适合经营分析、管理驾驶舱、业绩复盘、核心指标总览。',
    productCategory: 'data-workbench',
    appShell: 'analytics-board',
    pageBlueprints: ['经营总览', '指标趋势', '分布分析', '异常提醒', '明细透视'],
    navigationStrategy: '顶部指标导航 + 双列分析区 + 明细区',
    interactionPatterns: ['指标切换', '趋势对比', '分布查看', '异常提醒', '明细下钻'],
    dataStrategy: '指标数据 + 趋势数据 + 本地存储',
    seedDataStrategy: '经营指标样本数据',
    developerPromptHints: ['突出经营指标与趋势', '保持高层汇报风格', '减少后台表单感'],
  },
  {
    id: 'monitoring-center',
    name: '运营监控中心',
    description: '适合实时监控、运行态势、SLA 指标、异常波动追踪。',
    productCategory: 'data-workbench',
    appShell: 'analytics-board',
    pageBlueprints: ['监控总览', '实时指标', '波动趋势', '告警列表', '处置建议'],
    navigationStrategy: '顶部摘要 + 指标矩阵 + 趋势与告警并列',
    interactionPatterns: ['实时监测', '趋势比较', '异常查看', '告警处理', '指标筛选'],
    dataStrategy: '监控指标 + 告警数据 + 本地存储',
    seedDataStrategy: '监控与告警样本',
    developerPromptHints: ['强调实时性与风险感知', '突出告警与处置视图', '避免退化成普通统计报表'],
  },
  {
    id: 'faq-center',
    name: '帮助中心',
    description: '适合 FAQ、帮助中心、自助支持、常见问题检索。',
    productCategory: 'knowledge-hub',
    appShell: 'knowledge-search-content',
    pageBlueprints: ['搜索区', '问题分类', '问题列表', '答案详情', '推荐问题'],
    navigationStrategy: '顶部搜索 + 左侧分类 + 中间内容 + 右侧辅助区',
    interactionPatterns: ['搜索', '分类筛选', '问答浏览', '相关推荐', '常见入口'],
    dataStrategy: 'FAQ 数据 + 分类数据 + 本地存储',
    seedDataStrategy: '问答型知识数据',
    developerPromptHints: ['突出快速检索与常见问题', '强化答案可读性', '避免文档门户过重结构'],
  },
  {
    id: 'policy-library',
    name: '制度文档库',
    description: '适合制度库、规范文档、资料门户、内控知识沉淀。',
    productCategory: 'knowledge-hub',
    appShell: 'knowledge-search-content',
    pageBlueprints: ['文档搜索', '目录树', '文档详情', '关联资料', '更新记录'],
    navigationStrategy: '左侧目录树 + 中间文档内容 + 右侧摘要区',
    interactionPatterns: ['搜索', '目录展开', '文档浏览', '资料引用', '版本查看'],
    dataStrategy: '文档数据 + 分类数据 + 本地存储',
    seedDataStrategy: '制度与资料型内容',
    developerPromptHints: ['突出文档结构与目录层级', '强调制度资料的正式感', '避免退化成 FAQ 页面'],
  },
  {
    id: 'copilot-assistant',
    name: '企业智能助理',
    description: '适合企业 Copilot、分析助理、知识助理、办公助手。',
    productCategory: 'ai-chat',
    appShell: 'chat-two-pane',
    pageBlueprints: ['会话列表', '消息流', '输入区', '推荐问题', '上下文侧栏'],
    navigationStrategy: '左侧会话历史 + 中央消息区 + 右侧上下文面板',
    interactionPatterns: ['多轮会话', '推荐提问', '上下文切换', '快捷操作', '消息反馈'],
    dataStrategy: '会话线程 + 消息数据 + 本地存储',
    seedDataStrategy: '办公助理对话样本',
    developerPromptHints: ['突出 Copilot 感与知识辅助', '弱化客服语气', '强化侧栏上下文与推荐提问'],
  },
  {
    id: 'service-desk-chat',
    name: '服务台问答',
    description: '适合客服助手、服务台问答、工单咨询、内部支持会话。',
    productCategory: 'ai-chat',
    appShell: 'chat-two-pane',
    pageBlueprints: ['会话列表', '消息流', '输入区', '问题推荐', '工单上下文'],
    navigationStrategy: '左侧历史 + 中间会话 + 右侧问题与工单信息',
    interactionPatterns: ['问题追问', '知识引用', '状态回溯', '快捷回复', '上下文联动'],
    dataStrategy: '服务会话 + 工单上下文 + 本地存储',
    seedDataStrategy: '客服问答样本',
    developerPromptHints: ['突出服务台与支持语境', '强调问题处理与上下文记录', '避免泛化成办公 Copilot'],
  },
  {
    id: 'approval-automation',
    name: '审批自动化',
    description: '适合审批流程、待办流转、节点处理、合规流转自动化。',
    productCategory: 'automation-workflow',
    appShell: 'workflow-board',
    pageBlueprints: ['流程列表', '流程节点', '执行状态', '待办队列', '规则说明'],
    navigationStrategy: '左侧流程列表 + 中间节点流 + 底部状态区',
    interactionPatterns: ['节点查看', '流程切换', '状态追踪', '规则说明', '待办处理'],
    dataStrategy: '流程数据 + 节点数据 + 本地存储',
    seedDataStrategy: '审批流样本数据',
    developerPromptHints: ['突出审批与流转状态', '强调节点顺序与待办信息', '避免泛化成图表或表格页'],
  },
  {
    id: 'ops-automation',
    name: '运维自动化',
    description: '适合任务编排、作业调度、运维流程、自动执行监控。',
    productCategory: 'automation-workflow',
    appShell: 'workflow-board',
    pageBlueprints: ['任务列表', '流程节点', '执行记录', '告警状态', '规则配置'],
    navigationStrategy: '左侧任务导航 + 中间流程编排 + 右侧执行状态',
    interactionPatterns: ['流程查看', '任务切换', '执行跟踪', '状态提醒', '规则说明'],
    dataStrategy: '任务流数据 + 执行记录 + 本地存储',
    seedDataStrategy: '自动化执行样本',
    developerPromptHints: ['突出任务执行与状态监控', '强调运维编排语境', '避免退化成审批待办页'],
  },
  {
    id: 'corporate-portal',
    name: '企业门户',
    description: '适合企业官网首页、内部统一入口、集团门户展示。',
    productCategory: 'portal-showcase',
    appShell: 'portal-hero-sections',
    pageBlueprints: ['门户首页', '业务入口', '公告资讯', '重点专题', '联系入口'],
    navigationStrategy: '顶部导航 + 首屏视觉区 + 多分区内容流',
    interactionPatterns: ['入口跳转', '专题切换', '资讯浏览', '内容推荐', '重点公告'],
    dataStrategy: '门户分区数据 + 本地存储',
    seedDataStrategy: '门户栏目与公告样本',
    developerPromptHints: ['突出企业形象与统一入口', '首页强调分区与重点内容', '避免退化成后台列表页'],
  },
  {
    id: 'campaign-landing',
    name: '活动着陆页',
    description: '适合活动专题、招商推广、会务报名、营销落地页。',
    productCategory: 'portal-showcase',
    appShell: 'portal-hero-sections',
    pageBlueprints: ['活动主视觉', '亮点介绍', '流程说明', '报名入口', 'FAQ'],
    navigationStrategy: '单页滚动 + 顶部锚点导航 + 重点行动按钮',
    interactionPatterns: ['分区浏览', '亮点展开', '报名填写', 'FAQ 查看', '行动转化'],
    dataStrategy: '活动信息 + 报名数据 + 本地存储',
    seedDataStrategy: '活动内容与报名样本',
    developerPromptHints: ['突出首屏转化与亮点展示', '强调营销节奏', '避免门户资讯过重结构'],
  },
  {
    id: 'training-center',
    name: '培训学习中心',
    description: '适合员工培训、课程学习、学习任务、成长计划。',
    productCategory: 'learning-exam',
    appShell: 'learning-dashboard',
    pageBlueprints: ['学习首页', '课程列表', '课程详情', '学习任务', '进度统计'],
    navigationStrategy: '顶部学习导航 + 左侧分类 + 主内容学习区',
    interactionPatterns: ['课程筛选', '学习进度查看', '任务切换', '内容阅读', '进度反馈'],
    dataStrategy: '课程数据 + 学习记录 + 本地存储',
    seedDataStrategy: '课程与学习任务样本',
    developerPromptHints: ['突出课程与学习进度', '强调任务驱动', '避免退化成知识库文档页'],
  },
  {
    id: 'exam-platform',
    name: '在线考试平台',
    description: '适合考试安排、试卷练习、成绩查看、考务演示。',
    productCategory: 'learning-exam',
    appShell: 'learning-dashboard',
    pageBlueprints: ['考试首页', '考试列表', '试卷详情', '答题入口', '成绩统计'],
    navigationStrategy: '顶部考试导航 + 主内容区 + 状态提示区',
    interactionPatterns: ['考试切换', '试卷查看', '状态提醒', '成绩浏览', '结果反馈'],
    dataStrategy: '考试记录 + 成绩数据 + 本地存储',
    seedDataStrategy: '考试与成绩样本',
    developerPromptHints: ['突出考试状态与成绩反馈', '强调答题与结果场景', '避免纯课程学习语气'],
  },
  {
    id: 'ordering-mall',
    name: '订货商城',
    description: '适合渠道订货、商品选购、订单下单、进货管理。',
    productCategory: 'commerce-transaction',
    appShell: 'commerce-board',
    pageBlueprints: ['商城首页', '商品列表', '商品详情', '订单列表', '下单表单'],
    navigationStrategy: '顶部分类导航 + 商品内容区 + 订单侧入口',
    interactionPatterns: ['商品筛选', '下单操作', '订单查看', '状态跟踪', '推荐商品'],
    dataStrategy: '商品数据 + 订单数据 + 本地存储',
    seedDataStrategy: '商品与订单样本',
    developerPromptHints: ['突出商品、订单与交易动作', '强调下单链路', '避免退化成普通台账后台'],
  },
  {
    id: 'procurement-mall',
    name: '采购商城',
    description: '适合企业采购、集中采购、供应商比价、采购清单。',
    productCategory: 'commerce-transaction',
    appShell: 'commerce-board',
    pageBlueprints: ['采购首页', '采购商品', '供应商详情', '采购单列表', '申请表单'],
    navigationStrategy: '顶部分类 + 中间采购内容区 + 右侧采购状态区',
    interactionPatterns: ['商品查看', '供应商比较', '采购申请', '订单追踪', '状态反馈'],
    dataStrategy: '采购商品 + 采购单数据 + 本地存储',
    seedDataStrategy: '采购清单与供应商样本',
    developerPromptHints: ['突出采购语境与供应商视角', '强调申请与状态链路', '避免商城风格过重营销感'],
  },
  {
    id: 'appointment-center',
    name: '预约服务中心',
    description: '适合门店预约、上门服务预约、咨询排期、服务登记。',
    productCategory: 'service-scheduling',
    appShell: 'schedule-board',
    pageBlueprints: ['预约首页', '服务列表', '预约详情', '时间排期', '预约表单'],
    navigationStrategy: '左侧服务分类 + 中间预约内容 + 右侧时间状态区',
    interactionPatterns: ['服务选择', '时间预约', '排期查看', '状态跟踪', '预约确认'],
    dataStrategy: '预约数据 + 服务排期 + 本地存储',
    seedDataStrategy: '预约记录与排期样本',
    developerPromptHints: ['突出预约与时间选择', '强调服务排期', '避免退化成审批或订单页'],
  },
  {
    id: 'shift-scheduler',
    name: '排班调度台',
    description: '适合值班排班、资源调度、班次调整、人员安排。',
    productCategory: 'service-scheduling',
    appShell: 'schedule-board',
    pageBlueprints: ['排班总览', '班次列表', '人员详情', '调度看板', '调整表单'],
    navigationStrategy: '顶部排班概览 + 中间调度区 + 底部状态区',
    interactionPatterns: ['班次查看', '调度切换', '人员安排', '状态提醒', '调整提交'],
    dataStrategy: '班次数据 + 人员排班 + 本地存储',
    seedDataStrategy: '班次与排班样本',
    developerPromptHints: ['突出时间轴与班次调度', '强调人员安排', '避免退化成普通任务表格'],
  },
  {
    id: 'delivery-hub',
    name: '项目交付平台',
    description: '适合项目交付、里程碑推进、交付状态管理、客户验收。',
    productCategory: 'project-delivery',
    appShell: 'delivery-workspace',
    pageBlueprints: ['交付总览', '项目列表', '里程碑详情', '交付任务', '验收记录'],
    navigationStrategy: '左侧项目导航 + 中间交付工作区 + 右侧状态侧栏',
    interactionPatterns: ['项目切换', '里程碑跟踪', '任务处理', '状态查看', '验收反馈'],
    dataStrategy: '项目数据 + 交付任务 + 本地存储',
    seedDataStrategy: '项目与交付记录样本',
    developerPromptHints: ['突出交付阶段与里程碑', '强调客户验收', '避免退化成通用运营后台'],
  },
  {
    id: 'implementation-collab',
    name: '实施协同中心',
    description: '适合实施计划、上线准备、问题跟踪、跨团队协同。',
    productCategory: 'project-delivery',
    appShell: 'delivery-workspace',
    pageBlueprints: ['实施首页', '任务清单', '问题详情', '协同看板', '处理表单'],
    navigationStrategy: '左侧阶段导航 + 中间任务协同区 + 右侧状态信息区',
    interactionPatterns: ['任务分派', '问题跟踪', '状态同步', '协同处理', '结果记录'],
    dataStrategy: '实施任务 + 问题记录 + 本地存储',
    seedDataStrategy: '实施任务与问题样本',
    developerPromptHints: ['突出协同推进与问题闭环', '强调跨团队配合', '避免退化成单纯工单系统'],
  },
];
